### ISSUE TITLE
Map with time.Time

### ISSUE THREAD

**Issue by asdine** [imdario/mergo#18]
Hi,

I can't manage to copy time variables from a map to a struct :

```go
type Bla struct {
	Name  string
	Birth time.Time
}
data := map[string]interface{}{
		"Name":  "Bla",
		"Birth": time.Now(),
}

b := Bla{}

err := mergo.Map(&b, data)
fmt.Println(err)
// nil

fmt.Println(b.Birth.IsZero())
// true
```

Am i missing something?

**Comment by imdario** [comment]
Quick tip: it works using a pointer for Birth.

    type Bla struct {
        Name strint
        Birth *time.Time
    }

I'm working in a test which also covers Merge. Actually it works with or without pointer, so it must be a bug in Map. Thanks for your report.

**Comment by imdario** [comment]
Ok, I had seen it. First, the "bug" is on Merge, not in Map as I said before (sorry, still :zzz:). I double quote "bug" because this behavior it is how Mergo works. I just didn't realize that [time.Time has no exported fields](https://golang.org/src/time/time.go?s=1855:2369#L29) so Mergo can merge.

As stated in the README:

> You can only merge same-type structs with exported fields initialized as zero value of their type and same-types maps.

Yes, it's a shame but it's because [reflect.Value.CanSet()](https://golang.org/pkg/reflect/#Value.CanSet) only works on exported fields:

> CanSet reports whether the value of v can be changed. **A Value can be changed only if it is addressable and was not obtained by the use of unexported struct fields.** If CanSet returns false, calling Set or any type-specific setter (e.g., SetBool, SetInt) will panic. 

The only workaround for you use case is to use a pointer to time.Time and Mergo will be happy to merge it because it doesn't need to go deeper in time.Time struct.

I don't close the issue until getting your confirmation.

**Comment by asdine** [comment]
Hi!

Using a pointer to time is totally ok for my use case.
Thank you for the tip :)

**Comment by imdario** [comment]
Cool! Closing issue. Thanks you for your patience.

**Comment by iampeter** [comment]
@imdario I have a similar issue with a type build upon `time.Time`:
```
type Date time.Time
```
The type is used for date-only JSON representation. I AM using a pointer to Date and `MergeWithOverwrite` does not work unfortunately. 

Could you help with this?

**Comment by ernsheong** [comment]
I understand that `var t time.Time` is an empty struct and not considered a zero-value and hence `time.Time` is not merged, but `*time.Time` is merged. 

Perhaps this is a special use case worth exploring, either by default or with a Transformer (preferred).
