### ISSUE TITLE
Issue with boolean type (bool)

### ISSUE THREAD

**Issue by strmaks** [imdario/mergo#24]
If struct has a boolean fields, merge result is prefer true value, but this is not correct.
Example:

```go
package main

import (
    "fmt"
    "github.com/imdario/mergo"
)

type Foo struct {
    A string
    B int64
    C bool
}

func main() {
    src := Foo{
        A: "one",
        C: true,
    }

    dest := Foo{
        A: "two",
        B: 2,
        C: false,
    }

    mergo.Merge(&dest, src)

    fmt.Println(dest)
    // Will print
    // {two 2 true}
    // but expected result is {two 2 false}
}
```

**Comment by imdario** [comment]
This is the expected behavior. As stated in README:

> Mergo is intended to assign only zero value fields on destination with source value.

The zero value of a boolean field is false. It isn't possible to avoid it even with a pointer because Merge follows the pointers too. So, when it finds a pointer to bool with false value, it will overwrite with a true value if src matching field is true.

If you have any doubt, don't hesitate to ask me.

**Comment by strmaks** [comment]
Thank you.

**Comment by TomUnequals** [comment]
For those of you who need it, @Pothulapati built a fork that solves this [here](https://github.com/Pothulapati/mergo/commit/5a1b1cee7b3f9022825154dea4dcf5fb0dceecb8).

**Comment by PamelaKelly** [comment]
>This is the expected behavior.

@darccio does this mean it is not possible to merge booleans at all using this tool then? If we cannot rely on it respecting a legitimate value of false? Or do you have a recommendation for how to get around this? 

It would be unfortunate if so as it would make it unusable for anyone with boolean values in their yaml, and otherwise the tool is brilliant. :(

**Comment by vtolstov** [comment]
i think that for bool case we need to add additional logic

**Comment by PamelaKelly** [comment]
> i think that for bool case we need to add additional logic

Do you mean in the mergo repo or where it is being called?

**Comment by vtolstov** [comment]
> > i think that for bool case we need to add additional logic
> 
> Do you mean in the mergo repo or where it is being called?

in mergo repo, but i dont know how to detect false vs not set =)

**Comment by emirot** [comment]
Here is 3 ways to handle merge boolean the way we would like:

- Using `mergo.WithOverwriteWithEmptyValue` https://github.com/darccio/mergo/issues/129#issuecomment-629811978 but the drawback is that empty values won't be kept
- Using a customBoolean Type see https://github.com/darccio/mergo/issues/129#issuecomment-629811978 
- Treat boolean as string
