### ISSUE TITLE
ErrNotSupported when merging structs

### ISSUE THREAD

**Issue by bdcribbs** [imdario/mergo#44]
When I attempt to merge two structs, I get an ErrNotSupported.  I poked into it a little bit, and ran across this comparison:

https://github.com/imdario/mergo/blob/7fe0c75c13abdee74b09fcacef5ea1c6bba6a874/mergo.go#L60

It looks to me like it is impossible for that condition to ever evaluate as `false`.

If kind is struct, then it’s `false && true`
If kind is map, then it’s `true && false`
If kind is anything else, then it’s `true && true`

Am I misreading that?

**Comment by imdario** [comment]
How are your structs? Thanks!

About this comparison, I agree it's kind of strange. I'll get around this soon.

**Comment by imdario** [comment]
Ok, it wasn't soon but I'm getting around this today. We must "open" the scope and understand what we are trying to achieve at this line. It belongs to the function `resolveValues` and it's called from `Merge` and `Map`.

As per Mergo's documentation:

> You can only merge same-type structs with exported fields initialized as zero value of their type and same-types maps.

> Additionally, you can map a map[string]interface{} to a struct (and otherwise, from struct to map), following the same restrictions as in Merge().

So, we need to check that source and destination are:

- both structs with equal type
- both maps with equal type
- a map and a struct (or otherwise)

If src or dst is anything else than those kinds (`reflect.Struct` and `reflect.Map`, so `true && true`), resolveValues must return `ErrNotSupported` as you are attempting to merge a value (or to this) that isn't supported.

The purpose of `resolveValues` is to refactor shared checks by `Merge` and `Map`. The condition only checks the destination. After calling this it's handled different in each function, according to the expected behavior.

So, what we are doing in this line? Checking if the destination is anything else than a `reflect.Map` or a `reflect.Struct`. We can write it in a more clear form as follows:

```go
if !(vst.Kind() == reflect.Struct || vst.Kind() == reflect.Map) {
```

As you can see, that condition would output the same truth table:

- If kind is `reflect.Struct`, then it’s `!(true || false)` therefore `false`
- If kind is `reflect.Map`, then it’s `!(false || true)` therefore `false`
- If kind is anything else, then it’s `!(false || false)` therefore `true`

Conclusion: it's a weird condition but it evaluates to false when it's one of the supported types.
